name: "FB fetch action"
description: "Fetch latest posts for a page"
inputs:
  page-id: # page id
    description: "FB page id"
    required: true
  page-token: # page token
    description: "FB page token"
    required: true
  data-folder:
    description: "Target folder path"
    required: false
    default: "./data/fb/"
  start-year:
    description: "Since year to fetch the posts"
    required: false
    default: 2022
runs:
  using: "node16"
  main: "dist/index.js"
