on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: update dist
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Build
        run: npm run build
      - name: Commit dist
        run: |
          git config --global user.email "build-bot"
          git config --global user.name "build-bot"
          git add dist
          git commit -a -m "Update dist."
          git push
